name: 4xFaceUpSharpDAT
model_type: GeneralGANModel
scale: 4
num_gpu: auto
manual_seed: 0

l1_gt_usm: False
percep_gt_usm: False
gan_gt_usm: False

resize_prob: [0.1, 0.2, 0.7]
resize_range: [0.85, 1.2]
gaussian_noise_prob: 0
noise_range: [0, 0]
poisson_scale_range: [0, 0]
gray_noise_prob: 0
jpeg_range: [95, 100]

second_blur_prob: 0.8
resize_prob2: [0.1, 0.2, 0.7]
resize_range2: [0.85, 1.2]
gaussian_noise_prob2: 0
noise_range2: [0, 0]
poisson_scale_range2: [0, 0]
gray_noise_prob2: 0
jpeg_range2: [95, 100]

gt_size: 128
queue_size: 180

datasets:
  train:
    name: FaceUpSharp # My own dataset, based on FFHQ images, additionally processed with contrast adaptive high boost filter
    type: RealESRGANDataset
    dataroot_gt: /home/phips/Documents/datasets/FaceUp/FaceUpSharp
    meta_info: /home/phips/Documents/datasets/FaceUp/meta_info.txt
    io_backend:
      type: disk

    blur_kernel_size: 7
    kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob: [0.65, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob: 0
    blur_sigma: [0.2, 0.8]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 7
    kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob2: [0.65, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob2: 0
    blur_sigma2: [0.2, 0.8]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.8

    gt_size: 128
    use_hflip: True
    use_rot: True

    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    
  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: /home/phips/Documents/datasets/FaceUp/val/hr
    dataroot_lq: /home/phips/Documents/datasets/FaceUp/val/x4
    io_backend:
      type: disk

network_g:
  type: DAT
  upscale: 4
  in_chans: 3
  img_size: 64
  img_range: 1.
  split_size: [8,32]
  depth: [6,6,6,6,6,6]
  embed_dim: 180
  num_heads: [6,6,6,6,6,6]
  expansion_factor: 4
  resi_connection: '1conv'

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64

path:
  pretrain_network_g: /home/phips/Documents/GitHub/traiNNer-redux-FJ-ext/experiments/pretrained_models/4xFaceUpDAT.pth
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d:
  param_key_d: params_ema
  strict_load_d: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [400000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1
  
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      "conv1_2": 0.1
      "conv2_2": 0.1
      "conv3_4": 1
      "conv4_4": 1
      "conv5_4": 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: 0.8
    style_weight: 0
    range_norm: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0

val:
  val_freq: 5000
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
