name: 4xHF2kLUDVAEDAT_light
model_type: GeneralGANModel
scale: 4
num_gpu: auto
manual_seed: 0

l1_gt_usm: False
percep_gt_usm: False
gan_gt_usm: False
high_order_degradation: False

datasets:
  train:
    name: HFA2k_LUDVAE_v1
    type: PairedImageDataset
    dataroot_gt: /home/phips/Documents/datasets/HFA2k_LUDVAE_v1/HR
    dataroot_lq: /home/phips/Documents/datasets/HFA2k_LUDVAE_v1/LR
    meta_info: /home/phips/Documents/datasets/HFA2k_LUDVAE_v1/meta_info.txt
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: True
    use_rot: True

    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    
  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: /home/phips/Documents/datasets/HFA2k_LUDVAE_v1/VAL_HR
    dataroot_lq: /home/phips/Documents/datasets/HFA2k_LUDVAE_v1/VAL_LR
    io_backend:
      type: disk

network_g:
  type: DAT
  upscale: 4
  in_chans: 3
  img_size: 64
  img_range: 1.
  depth: [18]
  embed_dim: 60
  num_heads: [6]
  expansion_factor: 2
  resi_connection: '3conv'
  split_size: [8,32]
  upsampler: 'pixelshuffledirect'

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64

path:
  pretrain_network_g: /home/phips/Documents/traiNNer-redux-FJ/experiments/pretrained_models/DAT_light_x4.pth
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d:
  param_key_d: params_ema
  strict_load_d: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [400000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  # perceptual loss (content and style losses)
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      "conv1_2": 0.1
      "conv2_2": 0.1
      "conv3_4": 1
      "conv4_4": 1
      "conv5_4": 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: 0.8
    style_weight: 0
    range_norm: false
    criterion: l1
  # contextual loss
  #contextual_opt:
  #  type: ContextualLoss
  #  loss_weight: 0.25
  #  layer_weights:
  #    "conv_3_2": 0.15
  #    "conv_4_2": 0.15
  #  max_1d_size: 64
  #  distance_type: "cosine"
  #  calc_type: "regular"
  #  z_norm: false
  #  crop_quarter: false,
  #  b: 1.0
  #  band_width: 0.5
  #  use_vgg: true,
  #  net: vgg19
  color_opt:
    type: ColorLoss
    criterion: "l1"
    loss_weight: 1.0
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0

val:
  val_freq: 1000
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
