name: 2xHFA2kCSRFormer_light
model_type: GeneralGANModel
scale: 2
num_gpu: 1
manual_seed: 0

l1_gt_usm: False
percep_gt_usm: False
gan_gt_usm: False
gt_usm: False
high_order_degradation : False
try_autoamp_g: False
try_autoamp_d: False

datasets:
  train:
    name: HFA2k_h264
    type: PairedImageDataset
    dataroot_gt: /home/phips/Documents/datasets/HFA2k
    dataroot_lq: /home/phips/Documents/datasets/HFA2k_h264
    io_backend:
      type: disk

    gt_size:  192
    use_hflip: true
    use_rot: true
    use_shuffle: True
    
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: /home/phips/Documents/datasets/HFA2kvalHR
    dataroot_lq: /home/phips/Documents/datasets/HFA2kvalLRh264
    io_backend:
      type: disk

# SRFormer light
network_g:
  type: SRFormer
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 16
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 60
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffledirect'
  resi_connection: '1conv'
  
network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64

path:
  pretrain_network_g: /home/phips/Documents/traiNNer-redux-FJ/experiments/2xHFA2kCSRFormer_light/models/net_g_135000.pth
  strict_load_g: true
  param_key_g: params_ema
  pretrain_network_d: /home/phips/Documents/traiNNer-redux-FJ/experiments/2xHFA2kCSRFormer_light/models/net_g_135000.pth
  param_key_d: params_ema
  strict_load_d: true
  resume_state: /home/phips/Documents/traiNNer-redux-FJ/experiments/2xHFA2kCSRFormer_light/training_states/135000.state

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1.5e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1

  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      "conv1_2": 0.1
      "conv2_2": 0.1
      "conv3_4": 1
      "conv4_4": 1
      "conv5_4": 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: 0.8
    style_weight: 0
    range_norm: false
    criterion: l1
  color_opt:
    type: ColorLoss
    criterion: "l1"
    loss_weight: 1.0
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

val:
  val_freq: 1000
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
